#!/usr/bin/env python3
"""Synchronize the runtime entry and standalone guides from canonical documents."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENTRY = ROOT / "CHATGPT.md"
CORE_FILES = [
    ROOT / "docs" / "chatgpt-5.5-project-instructions.md",
    ROOT / "docs" / "chatgpt-operational-integrity-rules.md",
]
FALLBACK = ROOT / "docs" / "chatgpt-5.5-all-in-one-instructions.md"
GUIDE = ROOT / "docs" / "chatgpt-transfer-instructions.md"
BASIC_TASK_FILES = [ROOT / "docs" / name for name in (
    "chatgpt-coding-rules.md", "chatgpt-proposal-review-rules.md", "chatgpt-blog-rules.md",
)]
EXTENDED_TASK_FILES = [ROOT / "docs" / name for name in (
    "chatgpt-engineering-task-rules.md", "chatgpt-knowledge-work-rules.md", "chatgpt-domain-packs.md",
)]
BEGIN = "<!-- BEGIN INLINED CORE RUNTIME (generated from docs/ — do not edit here) -->"
END = "<!-- END INLINED CORE RUNTIME -->"


def normalize(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.splitlines()).rstrip()


def rendered_runtime() -> str:
    return "\n\n".join(normalize(path.read_text(encoding="utf-8-sig")) for path in CORE_FILES)


def synchronized_text(text: str, core: str | None = None) -> str:
    if text.count(BEGIN) != 1 or text.count(END) != 1 or text.index(BEGIN) >= text.index(END):
        raise ValueError("CHATGPT.md must contain exactly one ordered inlined Core Runtime marker pair")
    before, remainder = text.split(BEGIN, 1)
    _, after = remainder.split(END, 1)
    return f"{before}{BEGIN}\n{rendered_runtime() if core is None else core}\n{END}{after}"


def generated_documents() -> dict[Path, str]:
    core = rendered_runtime()
    basic = "\n\n".join(normalize(path.read_text(encoding="utf-8-sig")) for path in BASIC_TASK_FILES)
    extended = "\n\n".join(normalize(path.read_text(encoding="utf-8-sig")) for path in EXTENDED_TASK_FILES)
    notice = "<!-- Generated by scripts/sync_runtime.py; edit canonical source docs instead. -->\n\n"
    return {
        ENTRY: synchronized_text(ENTRY.read_text(encoding="utf-8-sig"), core),
        FALLBACK: (
            "# ChatGPT All-in-One Instructions\n\n" + notice
            + "Copy for standalone Core, coding, proposal review, and blog guidance. "
            "Apply only the matching section. Use instead of CHATGPT.md. "
            "Historical filename retained for compatibility; no model requirement.\n\n"
            + core + "\n\n" + basic + "\n"
        ),
        GUIDE: (
            "# ChatGPT Transfer Instructions\n\n" + notice
            + "Optional full reference: Core and all ChatGPT task/domain guides. "
            "Use CHATGPT.md for normal task routing; do not preload this reference. "
            "Apply only sections relevant to the user's request.\n\n"
            + core + "\n\n" + basic + "\n\n" + extended + "\n"
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without writing files")
    args = parser.parse_args()
    try:
        # Render everything before writing so missing sources/markers cannot cause partial output.
        documents = generated_documents()
        if args.check:
            stale = [path for path, expected in documents.items()
                     if not path.is_file() or path.read_text(encoding="utf-8-sig") != expected]
            for path in stale:
                print(f"{path.relative_to(ROOT)} is out of sync; run python scripts/sync_runtime.py")
            if not stale:
                print("Generated runtime and guides are in sync.")
            return int(bool(stale))
        for path, expected in documents.items():
            encoded = expected.encode("utf-8")
            if not path.is_file() or path.read_bytes() != encoded:
                path.write_bytes(encoded)
    except (OSError, UnicodeError, ValueError) as error:
        print(f"Runtime synchronization failed: {error}")
        return 1
    print("Synchronized CHATGPT.md and standalone guides.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
